### ISSUE TITLE
oscap xccdf generate fix does not generate remediation for System Accounting with auditd rules

### ISSUE THREAD

**Issue by jeanyves-maisonnasse** [ComplianceAsCode/content#10013]
#### Description of problem:
oscap xccdf generate fix does not generate remediation for System Accounting with auditd rules

#### SCAP Security Guide Version:
scap-security-guide-0.1.65

#### Operating System Version:
Ubuntu 20.04

#### Steps to Reproduce:

```
sudo oscap xccdf eval --fetch-remote-resources \
                      --profile xccdf_org.ssgproject.content_profile_cis_level2_server \
                      --results-arf ./arf-before-remediation.xml \
                      --report ./report-before-remediation.html \
                      /opt/ssg/ssg-ubuntu2004-ds.xml
```

```
sudo oscap xccdf generate fix --fix-type bash \
                              --output ubuntu2004-remediation-script.sh \
                              --result-id xccdf_org.open-scap_testresult_xccdf_org.ssgproject.content_profile_cis_level2_server \
                              ./arf-before-remediation.xml
```

#### Actual Results:
The remediation script does not include remediation for audit.d rules whereas i have 66 failed rules on System Accounting with auditd

#### Expected Results:
As the remediation scripts are included in the security guide, i was exepting that the remediation script will include them

**Comment by dodys** [comment]
I believe you are not seeing the auditd remediations in the generated fix script because you are running on top of your audit results, and you might not have auditd installed and/or running, leading the result to be not-applicable. Could you please confirm it?

If you want to have a fix script for all the rules you can just run:
`oscap xccdf generate fix --fix-type bash --output ubuntu2004-remediation-script.sh --profile xccdf_org.ssgproject.content_profile_cis_level2_server /opt/ssg/ssg-ubuntu2004-ds.xml`

If you still want to generate the remediation for the audit result, then make sure you have auditd installed and running.

**Comment by dodys** [comment]
I'm closing this issue since we haven't received any feedback in a while.
Feel free to re-open this in case you still face issues.
