### ISSUE TITLE
bash script not available in the version 0.1.63 

### ISSUE THREAD

**Issue by Naranthiran** [ComplianceAsCode/content#10230]
#### Description of problem:
I am not able to find the bash scrip in the path /usr/share/scap-security-guide/bash/.

#### SCAP Security Guide Version:
0.1.63 

#### Operating System Version:
RHEL 9.1

#### Steps to Reproduce:

1.install the below list of packages  
openscap-1.3.6-4.el9.x86_64
openscap-scanner-1.3.6-4.el9.x86_64
scap-security-guide-0.1.63-5.el9.noarch

2. 
3.
4.

**Comment by jan-cerny** [comment]
Hi, This thing is specific for RHEL 9 and depends on how Red Hat decides to package this upstream project to their RPM packages. In RHEL 9, the amount of content has been reduced. One of the goals was to avoid duplicate content in the RPM and therefore make the RPM package smaller. The Bash scripts are basically duplicate data, because their contents is present inside the shipped data streams. Users can easily generate them from data streams using the `oscap xccdf generate fix` command.

$ oscap xccdf generate fix --profile YOUR_PROFILE_ID /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml > fix.sh
