### ISSUE TITLE
[affects stabilization] Ansible Playbooks contain not permitted shell commands

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#10893]
#### Description of problem:
During productization run of the downstream test `/CoreOS/scap-security-guide/Sanity/ansible-allowed-shell-commands` we have found that a generated Ansible Playbook contains shell commands that aren't allowed.

#### SCAP Security Guide Version:
Current upstream master branch as of 2023-07-21 as of HEAD a96ccb9

#### Operating System Version:
RHEL 9, RHEL 8 , RHEL 7

#### Steps to Reproduce:

1.` oscap xccdf generate fix --fix-type ansible --output <output.yml> <ds.xml>`

#### Actual Results:

Playbooks contains this inside:

```
grep -e '^\s*SHA_CRYPT_MIN_ROUNDS\s\+' /etc/login.defs || true
df --local | awk '{print $6}' | grep -v Mounted | grep -v '^/dev' || true
```

#### Expected Results:
No  failing output is produced by the downstream test .

#### Additional Information/Debugging Steps:
There was a similar issue in past (https://github.com/ComplianceAsCode/content/issues/10852) but this productization was run after this issue had been fixed.

**Comment by ggbecker** [comment]
Based on the conversation in

https://github.com/ComplianceAsCode/content/issues/10852#issuecomment-1643912731
https://github.com/ComplianceAsCode/content/issues/10852#issuecomment-1645491558

The test should be updated with a waiver for this specific case.

**Comment by marcusburghardt** [comment]
This line:
`df --local | awk '{print $6}' | grep -v Mounted | grep -v '^/dev' || true`
was fixed by in this commit: https://github.com/ComplianceAsCode/content/pull/10889/commits/4d4d66a520e287facab85de9086740d33abccf60

The fix affected the `no_host_based_files` rule but the same issue is also present on `no_user_host_based_files` too.
Ideally, it should be created a macro for this approach and use it on these three rules:
- dir_perms_world_writable_root_owned
- no_host_based_files
- no_user_host_based_files

The macro makes sense since more similar rules may require this approach in the future.

Regarding the `grep -e '^\s*SHA_CRYPT_MIN_ROUNDS\s\+' /etc/login.defs || true` line, it is present in the `set_password_hashing_min_rounds_logindefs` rule where the Ansible remediation definitely can be improved.

**Comment by marcusburghardt** [comment]
I am working in this issue. I should propose a PR soon.

**Comment by marcusburghardt** [comment]
PR is ready for review: https://github.com/ComplianceAsCode/content/pull/10912
