### ISSUE TITLE
AuthenticationServices profile does not appropriate features

### ISSUE THREAD

**Issue by jacobranz** [ComplianceAsCode/content#11137]
#### Description of problem:
I am running the RHEL 8 stig role on one of my disconnected environments... I have all of the systems joined using SAS (Safeguard Authentication Services) and SAS has its own authselect profile called "AuthenticationServices". When the STIG role runs and attempts to enable features such as 'with-pwhistory' and 'with-faillock' it fails saying that those features aren't available. 

Any idea on how to fix this? Switching to another profile (sssd) has the features I need, but I can no longer authenticate with domain creds.

#### Operating System Version:
RHEL 8

#### Steps to Reproduce:

1. authselect select AuthenticationServices
2. Run STIG role

#### Actual Results:
STIG fails saying unkown feature for AuthenticationServices

#### Expected Results:
Be able to enable all necessary profile features on the AuthenticationServices profile.

**Comment by marcusburghardt** [comment]
It is likely because this custom profile `AuthenticationServices` was not created in a way to support authselect features.

There are procedures to create custom profiles based on default profiles.

- https://docs.redhat.com/fr/documentation/red_hat_enterprise_linux/9/html/configuring_authentication_and_authorization_in_rhel/creating-and-deploying-your-own-authselect-profile_configuring-user-authentication-using-authselect

Using this procedure, the features of the original profiles are preserved.
This issue is not related to STIG profile or any content in the project, but is caused by a custom profile.
I would recommend to report this issue to the SAS maintainer.
