### ISSUE TITLE
Bash remediation hangs on Ubuntu 20.04/22.04

### ISSUE THREAD

**Issue by mpurg** [ComplianceAsCode/content#11208]
#### Description of problem:

Bash remediation hangs on command `groupmems -g sugroup -p` on Ubuntu 20.04 and 22.04.
The reasons is that `groupmems -p` on Ubuntu prompts for root's password even when run as root or via sudo.
 (https://bugs.launchpad.net/ubuntu/+source/shadow/+bug/2039541)

This command was introduced in PR #11192 

#### Steps to Reproduce:

1. ./build_product.sh ubuntu2204
2. scp build/bash/ubuntu2204-script-cis_level1_server.sh root@ubuntu2204:
3. ssh root@ubuntu2204 "bash ubuntu2204-script-cis_level1_server.sh"

#### Actual Results:
Remediation hangs on:
```
Remediating rule 63/289: 'xccdf_org.ssgproject.content_rule_ensure_pam_wheel_group_empty'
Password: 
```

#### Expected Results:
Remediation finishes normally.

**Comment by dodys** [comment]
@marcusburghardt fyi

**Comment by marcusburghardt** [comment]
> @marcusburghardt fyi
> 
> https://unix.stackexchange.com/questions/533260/why-does-groupmems-command-ask-for-a-password-even-when-executed-as-root

Thanks for the reference @dodys . So, I believe using the `groupmems` in `ensure_pam_wheel_group_empty` rule is causing more trouble them benefit. Perhaps we should use a very generic approach here so the Bash remediation and test scenarios work fine for all distros.

Since the final goal is to have the group without members, I think it would be fine to remove and recreated the group.
The downside of this approach is that this remediation would possibly change the GID. That was the reason in Ansible remediation I simply edited the `/etc/group` file. It is possible because the context of this rule is more about local groups.
We can align the Bash remediation with the Ansible remediation. What do you think?

This would also solve https://github.com/ComplianceAsCode/content/issues/11203
