### ISSUE TITLE
Rule audit_rules_privileged_commands fails after hardening on ANSSI High

### ISSUE THREAD

**Issue by Mab879** [ComplianceAsCode/content#11752]
#### Description of problem:
After you install 

#### SCAP Security Guide Version:
7a23c33

#### Operating System Version:
RHEL 8/9

#### Steps to Reproduce:

1. Install RHEL 8/9 with the ANSSI High
2. Run an Ansible scan on the ANSSI High profile
3. Observe the failure

#### Actual Results:
Rule fails

#### Expected Results:
Rule passes

**Comment by jan-cerny** [comment]
It fails because the OVAL finds these 4 privileged commands which don't have an audit rule in audit rules:
/usr/libexec/sssd/ldap_child
/usr/libexec/sssd/selinux_child
/usr/libexec/sssd/krb5_child
/usr/libexec/sssd/proxy_child

This happens only if Ansible is used to remediate the system. When Bash was used these 4 commands have audit rules.

**Comment by jan-cerny** [comment]
> It fails because the OVAL finds these 4 privileged commands which don't have an audit rule in audit rules:
> /usr/libexec/sssd/ldap_child
> /usr/libexec/sssd/selinux_child
> /usr/libexec/sssd/krb5_child
> /usr/libexec/sssd/proxy_child

I have discovered that running the Ansible Playbook for the second time adds these 4 offending objects to `/etc/audit/rules.d/privileged.rules` and makes the rule `audit_rules_privileged_commands` pass.

I suspect that these 4 offending objects can be created by an Ansible Task which is located after Ansible Task for `audit_rules_privileged_commands`. Most likely some Ansible Task that is related to SSSD, these are located by the end of the Ansible Playbook.
 
>  This happens only if Ansible is used to remediate the system. When Bash was used these 4 commands have audit rules.

There is a difference that the `ansible` variant of the  test is running the Ansible Playbook once whereas the `oscap` variant of the test is running the remediation twice.

**Comment by jan-cerny** [comment]
Most likely the cause is the Ansible Task `Ensure sssd is installed` which is a part of remediation for rule `package_sssd_installed`. This Ansible Task installs the packages that own these offending files, specifically packages `sssd-krb5-common`, `sssd-ipa` and `sssd-proxy` which are dependencies of the `sssd-common` package. This Ansible Task is located later than the Ansible Task for the rule `audit_rules_privileged_commands`.

**Comment by vojtapolasek** [comment]
I can confirm this. I tried to reorder rules so that audit_rules_privileged_commands comes after all rules which install packages, but I am afraid it is currently not possible because the rule audit_rules_privileged_commands is in the "system" group and the rule package_sssd_installed is in the "services" group. Ordering of these groups is hardcoded. Do you agree @jan-cerny ?

**Comment by jan-cerny** [comment]
Yes, I'm looking into the same thing right now and tried to do something like that and it occurs that this ordering of groups is hardcoded in our build system https://github.com/ComplianceAsCode/content/blob/faa019d53eed0ff510a2ad39e1c9bbc463562bd3/ssg/build_yaml.py#L458.

**Comment by jan-cerny** [comment]
We could avoid it by moving the SSSD from services to system.
