### ISSUE TITLE
dnf-automatic_apply_updates rules in fail after Ansible remedation

### ISSUE THREAD

**Issue by Mab879** [ComplianceAsCode/content#11772]
#### Description of problem:
dnf-automatic_apply_updates rules in fail after Ansible remedation.

#### SCAP Security Guide Version:
978d2c6

#### Operating System Version:
RHEL 9

#### Steps to Reproduce:

1. Remediate System with anssi_bp28_high using Ansible
2. Scan the system
3. Observe the failure
4.

#### Actual Results:
Rule fails

#### Expected Results:
Rule passes

#### Additional Information/Debugging Steps:

- https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/managing_software_with_the_dnf_tool/assembly_automating-software-updates-in-rhel-9_managing-software-with-the-dnf-tool#doc-wrapper
- https://dnf.readthedocs.io/en/latest/automatic.html

**Comment by marcusburghardt** [comment]
So, I have checked the remediation, OVAL and test scenarios for this rule. I also did some manual tests with the Ansible Playbook and didn't find any issue.

This remediation was recently enabled for RHEL 9 in https://github.com/ComplianceAsCode/content/commit/5210a71aeffffd12e3e4043ae4421a9d7bcb3697

I found some logs from relevant tests executed about 3 weeks ago, when the remediation was enabled for RHEL9 and this issue was filed. I observed that the `dnf-automatic_apply_updates` and `dnf-automatic_apply_updates` rules were failing with many other profiles and not only with `anssi_bp28_high`.

When investigating the Playbook logs I noticed the `dnf-automatic` package was installed by `package_dnf-automatic_installed` but, by any reason that I couldn't figure out, the tasks related to remediation in `dnf-automatic_apply_updates` and `dnf-automatic_apply_updates` were not even part of the Playbook.
Since the tasks were not executed, the `automatic.conf` file was not remediated and the default settings were not compliant. Therefore, the check failure was correct.

Surprisingly, checking the most recent tests I can see the Playbook includes these tasks, proper remediate the system and the check pass after remediation. So, for now this issue is no longer present.

I believe these issues manifested only in a very short period of time while the Ansible remediation was enabled and the tests were executed. Maybe it was just an unfortunate issue of synchronization. I am not sure, but the issue seems no longer valid.

I am closing this and the #11773
