### ISSUE TITLE
zipl_bootmap_is_up_to_date is failing after Ansible remediation

### ISSUE THREAD

**Issue by vojtapolasek** [ComplianceAsCode/content#11944]
#### Description of problem:

When applying Ansible playbook for OSPP or CUI profile, the rule gets skipped during remediation.

#### SCAP Security Guide Version:

Stabilization-v0.1.73, commit 0b096bc4d27936b5adf992817f6df250fe8a5501 

#### Operating System Version:

RHEL 8

#### Steps to Reproduce:

1. get access to S390X machine
2. ./build_product rhel8
3. apply ospp or cui Ansible playbook
4. perform oscap scan of the same profile

#### Actual Results:

The rule zipl_bootmap_is_up_to_date is shown as failed

#### Expected Results:

The rule zipl_bootmap_is_up_to_date is shown as passed

#### Additional Information/Debugging Steps:

I think this might be due to rule ordering. During the ansible remediation, there is the following task worth noticing:

```
    - name: "Update zIPL bootmap"
      command: /usr/sbin/zipl
      changed_when: True
      when: boot_bootmap.stat.mtime is defined and zipl_conf.stat.mtime is defined and  boot_bootmap.stat.mtime < zipl_conf.stat.mtime
```

I think it might happen that the remediation is skipped because timestamps on those files are OK. But then there are other Zipl related rules which get remediated and the condition is no longer true.
So maybe ensuring that this rule goes as the last of Zipl-related rules might be the solution.

**Comment by Mab879** [comment]
This will appear on RHEL 9 soon as well.

Should be fixable with rule ordering.

**Comment by jan-cerny** [comment]
I have reproduced this on a s390x machine.

I have found in the ARF results that the rule `zipl_bootmap_is_up_to_date` fails because the files in the `/boot/loader/entries` directory are newer than file `/boot/bootmap`.

The reason is that there are some Tasks that run `grubby` that are run after the task for  `zipl_bootmap_is_up_to_date`.  They are part of rules `zipl_page_poison_argument` and `zipl_slub_debug_argument`. This could be solved by changing the rule order so that `zipl_bootmap_is_up_to_date` is the last.

Another problem is that the Ansible Task for the `zipl_bootmap_is_up_to_date` has the `when` statement misaligned with the OVAL check, the condition doesn't check for  the files in the `/boot/loader/entries` directory but OVAL checks them. There is a TODO for that in the Ansible remediation code.
