### ISSUE TITLE
oscap-docker should inspect container/image for disabled kernel capabilities

### ISSUE THREAD

**Issue by thetuxracer** [ComplianceAsCode/content#1350]
The report should mention the capabilities that the container runs with and without. This will help user to gain an understanding of the various capabilities that a container can run with and makes user aware of the necessities of each. By running the container with only the bare minimum capabilities, the attack surface is reduced to quite an extent.

**Comment by jan-cerny** [comment]
I discussed this issue today with @iankko.

An information about the additional or removed capabilities can be easily obtained by the `docker inspect` command. The problem that we see here is that OVAL language that is used to write checks in SCAP Security Guide **is not able to** run any external command. AFAIK this is also not possible to read from the list of processes provided by `ps`, since I don't know which child of docker belongs to which container.

@thetuxracer Are you aware of any way how to get information about capabilities of a running container by reading from file? Is this information stored somewhere?

**Comment by jan-cerny** [comment]
Another problem that I see here is that this is more likely a runtime check. We would like to know about capabilities of runnign containers. This is usually specified by adding an option to `docker run` command, e.g.: `docker run -d --cap-add sys_admin rhel7 sleep 1` Therefore it is not specified in configuration files or in Dockerfile.

But currently in SCAP Security guide we check for configuration, not for runtime. The policies that we provide are called " Guide to the Secure Configuration of Red Hat Enterprise Linux 7", so we are not checking what is running right now in our policies, but usually we check the content of configuration files. 

@mpreisler @iankko What do you think about this "problem"?

**Comment by ybznek** [comment]
I haven't investigated it deeply, we could try to read files like that `/var/lib/docker/containers/823d1ae5dad94565f72e8131443dc703dede2691ffb4a26d0402c80580e4cd21/hostconfig.json`. But It could change with docker versions, so I don't recommend this.

**Comment by jan-cerny** [comment]
@ybznek Thanks for the idea. 

Just for record we shouldn't forget that docker uses whitelist approach for capabilities. Some of them are turned on by default. However I think that the best practice with capabilities is to allow only necessary capabilities for running the containerized app, and turn off the others.

**Comment by jan-cerny** [comment]
@thetuxracer @mpreisler  What about atomic LABEL RUN ? Should we somehow detect that the Dockerfile used for building the image contains directives for atomic? These labels can specify various options for using the conatiner. I am pointing out this because using those labels you can specify Linux capabilities by specifying arguments of the `docker run` command.  See https://github.com/projectatomic/atomic/blob/master/docs/atomic-run.1.md

**Comment by thetuxracer** [comment]
@jan-cerny I missed this thread somehow.

The dockerfile is the best source of checking capabilities, although parameters can be overrun while starting the container using `docker run` and passing command line args. However, assuming we have a way to "inspect" the container at runtime, its the user who specifies a container to the openscap daemon , and hence it wont be possible to override arguments declared in the dockerfile.

Now it just remains a question of being able to either slurp output (which as already mentioned is not possible, neither is a good approach) or checking the filesystem of the container when we have mounted it, so to speak. 

Does that sound agreeable?

PS: There is a project called dockerfile_linter from another Redhatter, that examines the image, but it still needs to be called externally.

**Comment by matejak** [comment]
This issue is basically an idea for a new rule. The rule itself is questionable, so I am closing this.
