### ISSUE TITLE
hidepid=2 should be enabled

### ISSUE THREAD

**Issue by trevor-vaughan** [ComplianceAsCode/content#1648]
A warning caveat should be placed in EL7 systems that note that setting the `gid=` option on the `/proc` mount will necessitate starting `mcstransd` with the same Group option if it is in use.

Enabling `hidepid=2` enhances least privilege protections on the system by ensuring that users can only see the processes for which they are responsible.

See `proc(5)` for additional details.

**Comment by trevor-vaughan** [comment]
Additional information: This appears to map cleanly into `AC-3` and `AC-6` from NIST 800-53.

**Comment by shawndwells** [comment]
Since you've had this enabled in SIMP for awhile... any tips on how life changed post-enablement?

Meaning the new requirements (e.g. OSPP) leave it up to the operating system vendors to decide what settings would be a good idea. Would this be akin to enabling SELinux in RHEL5 and telling everyone good luck? Or in your opinion has it matured enough?

(many Red Hatters may be biased... really interested in your thoughts!)

**Comment by trevor-vaughan** [comment]
@jan-cerny What's unclear about this?

**Comment by yuumasato** [comment]
In #8288 a rule for this was implemented and together with a variable `/proc` can now be mounted with `hidepid=2`
In the profile add the following:
- `mount_option_proc_hidepid`
- `var_mount_option_proc_hidepid=2`
