### ISSUE TITLE
gpgcheck Enabled In Main Dnf Configuration

### ISSUE THREAD

**Issue by ybznek** [ComplianceAsCode/content#1727]
On my Fedora system `/etc/yum.conf` and `/etc/dnf/dnf.conf` exist.

If at least one of that config files contains `gpgcheck=1`, SSG rule will pass.

expected state:
rule will fail, if at least on of that files doesn't contain `gpgcheck=1`

**Comment by matejak** [comment]
Update: Both files exist on Fedora 29, and they may contain repository definitions. Those repositories may enable or disable `gpgcheck`. The check should also go through other files where repositories are defined, and check for gpgcheck status there as well.

**Comment by JaskaranNarula** [comment]
Question: @yuumasato @ybznek  does this stuff needs to be written in bash or xml ? 
Also, if bash then do I have to consider epel as well as in the rule ?

**Comment by yuumasato** [comment]
@JaskaranNarula This issue was about updating the OVAL (xml) of [ensure_gpgcheck_globally_activated](https://github.com/ComplianceAsCode/content/tree/master/linux_os/guide/system/software/updating/ensure_gpgcheck_globally_activated) to check both `/etc/yum.conf` and '/etc/dnf/dnf.conf`, and  Bash remediation should follow as well.

But on F31 the original issue doesn't seem to manifest anymore, it contains only `/etc/dnf/dnf.conf` file, so I think this can be closed.

**Comment by marcusburghardt** [comment]
No longer an issue.
