### ISSUE TITLE
[DISA] TMOUT issue on Rhel 7

### ISSUE THREAD

**Issue by david-paige-ctr** [ComplianceAsCode/content#2233]
I am having an issue with the TMOUT check on Rhel7 as described in RHEL-07-040160.

I have the line "TMOUT=600" in /etc/bashrc

This check fails unless I put the statement in the /etc/profile.d/ directory.  This statement passes the check:
echo "TMOUT=600" > /etc/profile.d/tmout.sh

It could also be that the STIG specified /etc/bashrc in the "Check Content" field, and /etc/profile in the "Fix Text" field.

**Comment by shawndwells** [comment]
On 8/10/17 2:31 PM, david-paige-ctr wrote:
>
> I am having an issue with the TMOUT check on Rhel7 as described in
> RHEL-07-040160.
>
> I have the line "TMOUT=600" in /etc/bashrc
>
> This check fails unless I put the statement in the /etc/profile.d/
> directory. This statement passes the check:
> echo "TMOUT=600" > /etc/profile.d/tmout.sh
>
> It could also be that the STIG specified /etc/bashrc in the "Check
> Content" field, and /etc/profile in the "Fix Text" field.
>

Can you kindly let DISA know about their mismatch? You can reach them
via disa.stig_spt@mail.mil.

In terms of "correctness", there are a dozen places you could put the
TMOUT setting. In SCAP Security Guide we scan both /etc/profile.d and
/etc/profile. These were chosen over /etc/bashrc because they're sourced
by all shells -- not just bash.

**Comment by david-paige-ctr** [comment]
I notified DISA about this issue in July.  Hopefully a corrected version will make it into the next update.

**Comment by shawndwells** [comment]
assigning to self to resolve for 0.1.39 release. Might just be double checking SSG does not have this bug before closing.

**Comment by redhatrises** [comment]
Looks like this has been fixed already. @david-paige-ctr please reopen if there is still a problem.
