### ISSUE TITLE
Add support for SCE

### ISSUE THREAD

**Issue by btaidm** [ComplianceAsCode/content#2363]
Would it possible to start adding in support for the Script Check Engine. I feel like this will be useful for other people to start developing content that doesn't have OVAL definitions, such as other Linux distributions.

**Comment by jan-cerny** [comment]
@btaidm Hi, I think it would be possible to support SCE. But it depends on what it would be used for.

Did you mean to use SCE for checking vulnerabilities (CVEs) in software packages? Or do you mean to use SCE for configuration checks? 

Could you please describe your use-case more in detail?

**Comment by btaidm** [comment]
@jan-cerny I was thinking about configuration checking. I currently have a modification on my fork for Arch Linux, as some checks required using `pacman` which doesn't have OVAL definitions. As well as checking to make sure AV defs are update to date. I believe that this falls within the scope of the security-guides.

**Comment by jan-cerny** [comment]
We strongly prefer OVAL for configuration checks, but if something really isn't achievable by OVAL, I think we could use SCE. I'm afraid that there will be push-back against SCE in RHEL content, because people are using it with 3rd party scanners that don't support SCE. But for Arch Linux, why not? @redhatrises @shawndwells What do you think?

If you already have something, feel free to open a pull request, I'm sure you'll get a lot of feedback.

**Comment by redhatrises** [comment]
I haven't played with SCE. However if openscap-sce now becomes a dependency for installation of SSG, I am not sure that this would be the way to go by adding another installation dependency (might be a mute point). Additionally if SCE takes precendence over existing OVAL content (haven't checked to see), I think that that would be a no-go from the start.

**Comment by btaidm** [comment]
I would have to play with it for check precedence. Also It could be an additional flag in the cmake file that is defaulted to off. I believe that is how openscap is initially configured. Ideally SCE would only be used for initial checks while a developer learns OVAL, which can then be ported over. Also it would used for checks for which there is not an OVAL equivalent, as not everybody as time or is big enough to add changes to the OVAL language.

**Comment by shawndwells** [comment]
On 9/26/17 11:18 AM, redhatrises wrote:
> I haven't played with SCE. However if openscap-sce now becomes a
> dependency for installation of SSG, I am not sure that this would be
> the way to go by adding another installation dependency (might be a
> mute point).
Tools != Content

We can (and do) ship content in downstreams like RHEL with no
requirements for an interpreter.

> Additionally if SCE takes precendence over existing OVAL content
> (haven't checked to see), I think that that would be a no-go from the
> start.
+1. This is particularly worrying. If people start writing SCE because
it's perceived as easier, and then the content doesn't work with broader
tools like SPAWAR SCC, Tenable, etc, then both SCAP and SSG get egg on
their face.

That said.... if content authors are fully aware SCE only works with
OpenSCAP, and they're OK with that, who are we to stop them? There are
use cases for SCE, but IMHO it's our (the community's) job to nudge
people towards OVAL while recognizing certain things must be scripted
(especially for 3rd party products that don't have OVAL probes).

**Comment by mpreisler** [comment]
> +1. This is particularly worrying. If people start writing SCE because
> it's perceived as easier, and then the content doesn't work with broader
> tools like SPAWAR SCC, Tenable, etc, then both SCAP and SSG get egg on
> their face.
> 
> That said.... if content authors are fully aware SCE only works with
> OpenSCAP, and they're OK with that, who are we to stop them? There are
> use cases for SCE, but IMHO it's our (the community's) job to nudge
> people towards OVAL while recognizing certain things must be scripted
> (especially for 3rd party products that don't have OVAL probes).

+1

**Comment by Mab879** [comment]
Support for SCE has been added in #7075.
