### ISSUE TITLE
Implement "no remediation" remediation

### ISSUE THREAD

**Issue by dahaic** [ComplianceAsCode/content#2557]
#### Description of problem:
Some of the rules are deliberately without remediation. To help  contributors to distinguish between rule with remediation missing, and remediation not wanted, we should have a way to identify such cases.

#### SCAP Security Guide Version:
0.1.36

**Comment by jan-cerny** [comment]
@dahaic I think that there is a way which is to add a warning to the rule.yml. We already do this in https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/software/integrity/certified-vendor/installed_OS_is_vendor_supported/rule.yml and this warning is displayed also to users of HTML guide and HTML report. @dahaic Would you be satisfied with that?

**Comment by marcusburghardt** [comment]
There are cases like this described in the description in CIS, for example. There are requirements which can be automatically checked but not automatically remediated in a safe way. In these cases, we explicitly don't want to create a remediation because this would bring more risks to breaking a system than actually making it safer. For example, setting passwords in GRUB.

In this context, I would suggest a new status in the control files. This status could be "check only", for example. This way it is easy to recognize the rule was already assessed and it was considered that a remediation is not desired there.

**Comment by jan-cerny** [comment]
@marcusburghardt

I don't exactly remember the background of this issue, but I assume that the main problem is that there is some rule where people expect that a fail result would be fixed by a remediation, but the remediation **intentionally** isn't present in the rule but they opened bugzillas or tried to implement and submit a PR with remediation.

I still think that the warning in the rule.yml can mitigate the situation. @dahaic Would you be satisfied with that?

I think that adding a status to control files isn't good because 1. controls map to multiple rules so it would have to be a rule-status mapping dictionary 2. remediations are properties of rules 3. there can be multiple controls referencing the same rule so you would have to keep the status consistent 4. some profiles aren't generated from controls. 

An extension of the solution would be to add a key "remediation: none" to the rule.yml and have a check in the build system that when somebody adds a remediation to the rule the build will abort. That addresses a different part of the problem, so it would have to be used together with the aforementioned warning which is user facing.

**Comment by marcusburghardt** [comment]
Very good arguments @jan-cerny . The number `1` was enough to convince me that the solution is not in the control file.

In that case, I agree with the warning in the `rule.yml`. There is already a place where we communicate the users about any exception or other relevant information. Also, based on profiles I analysed, at the moment, there is not so many cases like this to justify the efforts on this new mechanism in the build system. I would solve this issue with the warning for now and keep this idea (I liked it) to increment the build system in the backlog for a better opportunity. Would you agree?

**Comment by jan-cerny** [comment]
@marcusburghardt Yes, I agree.

@dahaic and you?

**Comment by marcusburghardt** [comment]
These are cases are uncommon and can be treated on demand by including a warning.
