### ISSUE TITLE
CMake uses empty marker files with a misleading name in `roles` directory

### ISSUE THREAD

**Issue by dahaic** [ComplianceAsCode/content#2639]
#### Description of problem:
There are files in `build/roles` directory, called `all-roles-{product}-{yml,sh}`. These files are generated empty.

#### SCAP Security Guide Version:
Upstream   Thu Mar 1 10:39:22 2018 -0500

#### Steps to Reproduce:

1. Build SSG
2. Look into `build/roles`
3.
4.

#### Actual Results:
Empty files!

#### Expected Results:
No empty files!

**Comment by mpreisler** [comment]
This is by design, it's not supposed to be a role, it's just a build system marker file. We use it to mark the timestamp all the roles were built to know whether we should rebuild.

**Comment by dahaic** [comment]
@matejak ^^ :)

**Comment by matejak** [comment]
Although this is not a bug, but rather a design decision, I see some issues with it:
- filenames are misleading - `all-roles-{product}-{yml,sh}.marker_file` would be a better choice.
- I don't like usage of markers, I think that build system should decide based on real files rather than on some dummy markers.

**Comment by mpreisler** [comment]
Yeah, I agree.

**Comment by jan-cerny** [comment]
Fixing the title because it's expected that those files are empty, but the real issue is that it's confusing @dahaic that CMake uses empty marker files with a misleading name to mark that Ansible playbooks and Bash scripts.

@matejak Do yo think we have to fix the misleading filenames as a part of #4276 ? If yes, which of the 2 solutions do you prefer?

**Comment by marcusburghardt** [comment]
It is long time outdated.
