### ISSUE TITLE
RHEL-07-010240 - Nessus needs clarification about filtering users

### ISSUE THREAD

**Issue by linuxdan** [ComplianceAsCode/content#3565]
#### Description of problem:
The STIG makes no mention about which logins should/should not be checked on this.
Nessus flags "nfsnobody" which has a shell of /sbin/nologin
The only way to get Nessus to change is to change the STIG
because they do EXACTLY what the STIG tells them do do.
No more.  No less. (Mostly)

#### Operating System Version:
RHEL 7.5

**Comment by redhatrises** [comment]
This should be opened and discussed with DISA and nessus. In general, the `nfsnobody` uid shouldn't be used on secure systems as it changes user ids which prevents audit log correlation.

**Comment by linuxdan** [comment]
@redhatrises 
I thought this was the “forum” to discuss stuff with DISA

**Comment by shawndwells** [comment]
There's a general upstream->downstream relationship. Once things are fixed here, the fixes make their way into DoD and NIST baselines. @tedbrunell is working with DISA to make that a faster and easier process.

Roughly:
`````
ComplianceAsCode Upstream Release (day 0)
             |-----> RHEL (few months after upstream release)
                             |------> DISA STIG (up to 2 years after RHEL release)
                             |------> DoD Configuration Baseline (days after RHEL release)
                             |------> NIST National Checklist (days after RHEL release)
`````

**Comment by redhatrises** [comment]
In addition to what @shawndwells says, we typically don't handle issues with 3rd party products and the stig.

**Comment by linuxdan** [comment]
@redhatrises 
I understand, but if I open a bug support ticket with Tenable, their mantra is, “We are doing what the STIG says”.  
Can you suggest another path to getting changes into the STIG ?
As I do not (currently) work on a DoD sponsored contract, DISA won’t talk to me.

**Comment by shawndwells** [comment]
@linuxdan falling back to the upstream->downstream comment. By ensuring the fix is in ComplianceAsCode (upstream), there's assurance that RHEL content, NIST, and DoD config guides will get the update when they're rebased.

The next time Red Hat submits vendor recommended guidance to DISA, through the Vendor STIG process, the changes will be included. Hopefully that helps amplify the voices of people not on DoD contracts but follow DISA guidance.

Outside of all this, IMHO, DISA does a good job of listening. Pinging them over EMail through disa.stig_spt@mail.mil is useful -- even to give them a heads up.

**Comment by linuxdan** [comment]
@shawndwells 
Thanks for the detail.  Understanding the whole schmess helps.
I guess what I was expecting is that I can submit corrections/enhancements/updates here to be included in Red Hat’s vendor recommended guidance to DISA.

If I am mistaken, please redirect me.

**Comment by shawndwells** [comment]
On 10/30/18 6:34 PM, Daniel E. White wrote:
>
> @shawndwells <https://github.com/shawndwells>
> Thanks for the detail. Understanding the whole schmess helps.
> I guess what I was expecting is that I can submit 
> corrections/enhancements/updates here to be included in Red Hat’s 
> vendor recommended guidance to DISA.
>

That's exactly how it works.

There is also participation by other vendors, like Oracle and Ubuntu, 
where this will trickle into as well :)
>
> If I am mistaken, please redirect me.
>

-- 
Shawn Wells
Chief Security Strategist
North America Public Sector
shawn@redhat.com   |   443-534-0130

**Comment by linuxdan** [comment]
@shawndwells 
OK, then why was this issue closed ?

**Comment by redhatrises** [comment]
> On 10/30/18 6:34 PM, Daniel E. White wrote: @shawndwells <https://github.com/shawndwells> Thanks for the detail. Understanding the whole schmess helps. I guess what I was expecting is that I can submit corrections/enhancements/updates here to be included in Red Hat’s vendor recommended guidance to DISA.
> That's exactly how it works. There is also participation by other vendors, like Oracle and Ubuntu, where this will trickle into as well :)
> […](#)
> If I am mistaken, please redirect me.
> -- Shawn Wells Chief Security Strategist North America Public Sector shawn@redhat.com | 443-534-0130

Disagree here... This is how we would like it to work, but Nessus may or may not choose to take changes from us. To be more precise, they typically implement their content in a proprietary way to comply with DISA.

Also, nfsnobody isn't mentioned in the STIG or benchmarks one bit, so it is a bug purely in the Nessus content. Also, the existence of `nfsnobody` can be a security concern, because if nfsnobody is used, it means that remote nfs users are not being tracked correctly on the system or in the audit log essentially making them anonymous users. So, Nessus is creating a more secure environment by remove nfsnobody from the users even if nfsnobody is a service account.

**Comment by linuxdan** [comment]
@redhatrises 
I think you miss the point of this issue.
The title of the rule is “Passwords must be restricted to a 24 hours/1 day minimum lifetime.”
Login “nfsnobody” has no password, so how can it be restricted ?

**Comment by linuxdan** [comment]
> or there is a bug in the DISA benchmark which would mean a ticket with DISA needs to be open.
How do I open a DISA bug ticket ?
I tried emailing them and was asked who my DoD sponsor was.
