### ISSUE TITLE
Ansible lineinfile doesn't rememdiate gpgcheck settings with multiple repos in a single file

### ISSUE THREAD

**Issue by redhatrises** [ComplianceAsCode/content#3810]
#### Description of problem:
Ansible lineinfile doesn't rememdiate gpgcheck settings with multiple repos in a single file.
It just does the last found match. Users would expect to be secure and compliance with policy after running an Ansible remediation, but that is not the case.

#### SCAP Security Guide Version:
Master

#### Operating System Version:
All

#### Steps to Reproduce:

1.
2.
3.
4.

#### Actual Results:
Only the last gpgcheck is changed in a multi-repo yum/dnf repo file.

#### Expected Results:
All repos have gpgcheck added or changed to gpgcheck=1

**Comment by caitelatte** [comment]
This makes sense and seems pretty easy to fix by using the [Ansible replace module](https://docs.ansible.com/ansible/latest/modules/replace_module.html#replace-module) instead of `lineinfile` for the [`ensure_gpgcheck_never_disabled` ansible playbook](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/software/updating/ensure_gpgcheck_never_disabled/ansible/shared.yml).

The bash remediation already does this as it uses the `g` flag in its sed substitution.

A straight up replacement with `replace` will lose the behaviour where `lineinfile` currently creates the line if it doesn't exist, since there's no equivalent to `create` in replace.

Given the intent of the rule is to remove any lines, I'd like to replace the `lineinfile` 

> remove any lines from files in <tt>/etc/yum.repos.d</tt> of the form:
> <pre>gpgcheck=0</pre>

I've made pull request https://github.com/ComplianceAsCode/content/pull/5094 to use `replace` instead.
