### ISSUE TITLE
sshd_enable_warning_banner should respect issue.net

### ISSUE THREAD

**Issue by comps** [ComplianceAsCode/content#4397]
sshd_enable_warning_banner currently checks only for `/etc/issue` and fails when it's not configured as `Banner` in `sshd_config`.

However many (most) systems use `/etc/issue.net`, when present, for users connecting over the network (eg. via ssh).

The rule should at least support checking for both, remediation would be subject to debate/optinion/compatibility.

Note that `banner_etc_issue` has a similar issue; it should probably check for **and** remediate both `/etc/issue` and `/etc/issue.net`.

**Comment by redhatrises** [comment]
Most systems these days actually do not configure `/etc/issue.net` because it is viewed as a legacy telnet-ism. In addition, `/etc/issue` is preferred over `/etc/issue.net` because `/etc/issue` is for local **and** network settings whereas `/etc/issue.net` is for network only settings. Many security catalogs have removed `/etc/issue.net` for this reason.

**Comment by shawndwells** [comment]
Could we create a new rule?

e.g. a ``sshd_enable_warning_banner_etc_issue`` which only evaluates if SSH is using /etc/issue, and another rule ``sshd_enable_warning_banner _etc_issue_net`` which evaluates when SSH is using /etc/issue.net? The idea being ``sshd_enable_warning_banner _etc_issue_net`` would result in ``notapplicable`` for most use cases?

**Comment by redhatrises** [comment]
Closing as projects like Cockpit and others are only using `/etc/issue`.
