### ISSUE TITLE
No support for Fedora 31?

### ISSUE THREAD

**Issue by atgreen** [ComplianceAsCode/content#5081]
#### Description of problem:
xccdf eval of standard profile on a Fedora 31 box show notapplicable for everything.

#### SCAP Security Guide Version:
Latest from upstream (as of Dec 24, 2019)

#### Operating System Version:
Fedora 31

#### Steps to Reproduce:

1. Run "oscap xccdf eval --profile=standard --report=report.html ./ssg-fedora-xccdf.xml" on a Fedora 31 box.
2.
3.
4.

**Comment by jan-cerny** [comment]
Hi,

Thanks for contacting us. The problem is with the CPE identifiers and CPE dictionary which is a technology that we use to detect Fedora version. Indeed, Fedora 31 is missing in our enumeration list. I will add it.

As a workaround, you can use the "datastream" file `ssg-fedora-ds.xml` instead of `ssg-fedora-xccdf.xml`. Datastream is a container that contains all files needed for the evaluation in a single XML and it also contains a CPE dictionary which overrides the CPE dictionary shipped in `openscap` package and doesn't check Fedora version to detect that installed OS is Fedora. Anyway, we always recommend to use datastream file.
