### ISSUE TITLE
5.7 Ensure access to the su command is restricted (Scored)

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#5541]

**Comment by alexhaydock** [comment]
This control is partially satisfied by `use_pam_wheel_for_su` rule, but we need some more to align perfectly with the benchmark.

**Comment by yuumasato** [comment]
Just to confirm, is the missing part this section?

```
Run the following command and verify users in wheel group match site policy. If no users
are listed, only root will have access to su.
# grep wheel /etc/group
wheel:x:10:root,<user list>
```

This will require some kind of assessment whether the group matches the site policy.
We could have a variable with a list of users, but the set of users part of `wheel` group may differ per system/machine.

So may feeling is that this part is not easy to automate so that it works for most use cases.

I propose to keep the item as partial with a note.
