### ISSUE TITLE
Update Ansible C2S Role for Use With RHEL8

### ISSUE THREAD

**Issue by imareporter** [ComplianceAsCode/content#5573]
#### Description of problem:
Currently, the C2S role (https://github.com/RedHatOfficial/ansible-role-rhel7-c2s) is based on RHEL7. Will there be a RHEL8 edition of the C2S role released soon?

#### Operating System Version:
RHEL8

**Comment by redhatrises** [comment]
Thanks for asking the question!

This has been discussed here and there, and nothing has really been determined on if we will provide a C2S profile or role for RHEL8. The reason is is that a US Government agency owns the C2S naming and profile. Red Hat has yet to get clarification about we can create a C2S profile for RHEL8, if it is going to be renamed to C2E, or it is just going away all together.

**Comment by imareporter** [comment]
@redhatrises Understood, thank you for the feedback! :)
