### ISSUE TITLE
disable_host_auth needs to be renamed with sshd_ prefix

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#5627]
disable_host_auth needs to be renamed with sshd_ prefix

**Comment by jan-cerny** [comment]
It would be nice, but it will break existing tailoring files.

**Comment by matejak** [comment]
What about copy-pasting the rule to the old one and add a deprecation message to the old one?

**Comment by marcusburghardt** [comment]
This rule is used in many profiles and control files. The benefit of renaming it wouldn't justify the effort.

**Comment by shawndwells** [comment]
> This rule is used in many profiles and control files. The benefit of renaming it wouldn't justify the effort.

``sed`` can be used to automate changing strings/rule IDs.

**Comment by marcusburghardt** [comment]
We can't simply rename the rule. See [Agreements](https://github.com/ComplianceAsCode/content/issues/5627) for more details.

@shawndwells , if you are planning to propose a PR, you need create a new rule using the `sshd_` prefix, follow the deprecation process in the former rule and update all profiles and control files.

There is a benefit on that in order to keep consistency in the project. But the benefit is uniquely aesthetic.
Considering the current usage of this rule and consequently the duplication it will cause in many datastreams, I don't think it is worth or even aggregate enough value to the project.
In addition, this is not an isolated case in the project and is not a real issue.

Since the issue has reopened, we can keep it open a little longer. If no one sends a PR for this, the issue will be closed.

**Comment by Mab879** [comment]
No PR, closing.
