### ISSUE TITLE
High RAM usage during oscap scan

### ISSUE THREAD

**Issue by captainwasabi** [ComplianceAsCode/content#5852]
#### Description of problem:
RAM usage goes through the roof right at the end of a scan (centos7 baseline). Is this expected?

#### SCAP Security Guide Version:
latest Centos 7

#### Operating System Version:
Centos7.8 

#### Steps to Reproduce:

1. Run scan
2. run top and watch ram grow (virt and res)
3.
4.

**Comment by ggbecker** [comment]
We are aware of some memory issues regarding OpenSCAP scanner.

This bugzilla might be related: https://bugzilla.redhat.com/show_bug.cgi?id=1824152

I suggest you creating an issue on OpenSCAP project since it's definitely a problem on OpenSCAP side. 

Also if you can share more information on which exact command you are running and which security content you are using along with their versions that will help a lot to debug the issue.

Please create the issue using this link: [https://github.com/OpenSCAP/openscap/issues/new](https://github.com/OpenSCAP/openscap/issues/new)

I'm closing this one since it's not a problem with ComplianceAsCode/content project.
