### ISSUE TITLE
Not enough tests - Ubuntu 1804

### ISSUE THREAD

**Issue by FF186** [ComplianceAsCode/content#6112]
#### Description of problem:
I want to test security on a Ubuntu 18.04, using the STIG-profile (or CIS), but the number of tests you have for Ubuntu 18.04 does not match the numbers of the STIG. 
I miss "actual security checks" for Ubuntu 18.04, e.g. tests for firewall (`ufw`) etc.

On that note, I want to be able to contribute, but do not understand your structure. Is it possible with a "idiot guide"?

#### SCAP Security Guide Version:
`1.2.15`

#### Steps to Reproduce:

1.  `oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_anssi_np_nt28_high --results /tmp/results.xml --report /tmp/report.html ssg-ubuntu1804-ds-1.2.xml`

#### Actual Results:
`45` Tests

#### Expected Results:
`200` Tests

**Comment by redhatrises** [comment]
Do you want the STIG or CIS for Ubuntu? If you want the STIG, it is located at https://public.cyber.mil/stigs/downloads/

As far as contributing, yes, the project is very complicated, and some of us are looking at how to make it more approachable and reduce a lot of the existing complexity and code dependencies. If you haven't already, check out the developer guide and see if that helps. 

The reason for the lack of Ubuntu checks is because no one from Canonical or Ubuntu has stepped up to actually support and maintain them. If we don't have someone do this, I am afraid the the content will always be in a sad state.

**Comment by konstruktoid** [comment]
Ubuntu is more focused on working with the CIS benchmarks; https://security-certs.docs.ubuntu.com/en/ and https://security-certs.docs.ubuntu.com/en/cis-18-16

**Comment by ggbecker** [comment]
There was definitely a huge amount of contributions from canonical people as you can see there better profiles for ubuntu:

https://github.com/ComplianceAsCode/content/tree/master/products/ubuntu2004/profiles
https://github.com/ComplianceAsCode/content/tree/master/products/ubuntu1804/profiles

And regarding contribution, you can easily start contributing using the gitpod integration that is explained here: https://complianceascode.github.io/template/2022/06/30/gitpod-integration.html

Closing this issue for now.
