### ISSUE TITLE
cmake symbol lookup error on RHEL8

### ISSUE THREAD

**Issue by Chalmiller** [ComplianceAsCode/content#7016]
#### Description of problem:
I am receiving the following error when trying to `./build_product rhel8` on a RHEL8 instance. I just tested the same source code on RHEL7 and the issue did not arise.

#### Operating System Version:
RHEL 8

#### Actual Results:
`cmake: symbol lookup error: cmake: undefined symbol: archive_write_add_filter_zstd`

#### Expected Results:
The product should be built

**Comment by Chalmiller** [comment]
@ggbecker Any ideas on why this would be occurring only for RHEL8?

**Comment by carlosmmatos** [comment]
@Chalmiller can you give more info on this? I'm assuming you've installed the necessary packages to build and compile since you've been able to do it on RHEL 7, but just in case - 

`yum install cmake make openscap-utils python3-pyyaml python3-jinja2`

Can you give us the output of:

- `cat /etc/redhat-release`
- `rpm -qa | egrep 'cmake|zstd'`

**Comment by cipherboy** [comment]
@Chalmiller I ran into this once when building JSS. It turns out I had a bad set of repos (mixed RHEL versions). It is due to a version mismatch between `cmake` and some of the libraries it depends on. I think this was around RHEL 8.2->8.3 timeframe. I'd double check your repos are correct and all packages are up to date. I suspect (but don't know for a fact) that cmake or one if is deps is missing a min-version requirement on one of the libraries. My 2c., HTH.

**Comment by carlosmmatos** [comment]
@cipherboy that's what I'm thinking as well.. some sort of version mismatch between cmake and its library dependencies. I've seen this when someone uses rhel packages on fedora as well.

**Comment by Chalmiller** [comment]
@carlosmmatos 

`cat /etc/redhat-release` => Red Hat Enterprise Linux release 8.3 (Ootpa)
`rpm -qa | egrep 'cmake|zstd'` => ```libzstd-1.4.4-1.el8.x86_64
zstd-1.4.4-1.el8.x86_64
cmake-filesystem-3.18.2-9.el8.x86_64
cmake-rpm-macros-3.18.2-9.el8.noarch
cmake-3.18.2-9.el8.x86_64
cmake-data-3.18.2-9.el8.noarch```

**Comment by carlosmmatos** [comment]
@Chalmiller So I talked to a few people about potential causes for this, and they've reported having seen similar issues with the libarchive package - for reference, my version is:
```
libarchive-3.3.3-1.el8.x86_64
```

Try either updating the package, or if it's already installed, maybe completely re-installing.

**Comment by Chalmiller** [comment]
Awesome, thank you @carlosmmatos! I'll try that out today and keep you posted on progress.

**Comment by Chalmiller** [comment]
@carlosmmatos Okay, so I just updated libarchive and that seems to have done the trick! Thank you again!
