### ISSUE TITLE
RHEL8 STIG - configure_gnutls_tls_crypto_policy fails after kickstart installation

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#7038]
#### Description of problem:
When a rhel8 is installed with STIG, `configure_gnutls_tls_crypto_policy` passes in installation phase. However, when a installation is done and you perform scan, the `configure_gnutls_tls_crypto_policy` rule result is fail.
Both stig version, gui and non-gui, are affected.

#### SCAP Security Guide Version:
`56a2765`

#### Operating System Version:
rhel8

#### Steps to Reproduce:
1. Install rhel8 with STIG security policy
2. Perform a scan

or

1. `python3 test_suite.py profile --libvirt qemu:///system test_suite_vm --datastream build/ssg-rhel8-ds.xml --xccdf-id scap_org.open-scap_cref_ssg-rhel8-xccdf-1.2.xml --mode online --remediate-using oscap xccdf_org.ssgproject.content_profile_stig`

#### Actual Results:
`configure_gnutls_tls_crypto_policy` fails

#### Expected Results:
`configure_gnutls_tls_crypto_policy` passes

#### Additional Information/Debugging Steps:
HTML report OVAL test results details:

Remediation scan - the **pass** result
`/etc/crypto-policies/back-ends/gnutls.config` content is:

> SYSTEM=NONE:+MAC-ALL:-MD5:+GROUP-ALL:+SIGN-ALL:-SIGN-RSA-MD5:-SIGN-DSA-SHA1:-SIGN-DSA-SHA224:-SIGN-DSA-SHA256:-SIGN-DSA-SHA384:-SIGN-DSA-SHA512:+SIGN-RSA-SHA1:%VERIFY_ALLOW_SIGN_WITH_SHA1:+CIPHER-ALL:-CAMELLIA-256-GCM:-CAMELLIA-128-GCM:-CAMELLIA-256-CBC:-CAMELLIA-128-CBC:-3DES-CBC:-ARCFOUR-128:+ECDHE-RSA:+ECDHE-ECDSA:+RSA:+DHE-RSA:+VERS-ALL:-VERS-DTLS0.9:-VERS-SSL3.0:-VERS-TLS1.0:-VERS-TLS1.1:-VERS-DTLS1.0:+COMP-NULL:%PROFILE_MEDIUM 

Final scan - the **fail** result
`/etc/crypto-policies/back-ends/gnutls.config` content is:

> SYSTEM=NONE:+MAC-ALL:-MD5:+GROUP-ALL:-GROUP-X25519:-GROUP-X448:+SIGN-ALL:-SIGN-RSA-MD5:-SIGN-RSA-SHA1:-SIGN-DSA-SHA1:-SIGN-ECDSA-SHA1:-SIGN-DSA-SHA224:-SIGN-DSA-SHA256:-SIGN-DSA-SHA384:-SIGN-DSA-SHA512:-SIGN-EDDSA-ED25519:-SIGN-EDDSA-ED448:+CIPHER-ALL:-CHACHA20-POLY1305:-CAMELLIA-256-GCM:-CAMELLIA-128-GCM:-CAMELLIA-256-CBC:-CAMELLIA-128-CBC:-3DES-CBC:-ARCFOUR-128:+ECDHE-RSA:+ECDHE-ECDSA:+DHE-RSA:+VERS-ALL:-VERS-DTLS0.9:-VERS-SSL3.0:-VERS-TLS1.0:-VERS-TLS1.1:-VERS-DTLS1.0:+COMP-NULL:%PROFILE_MEDIUM

**Comment by ggbecker** [comment]
The file `/etc/crypto-policies/back-ends/gnutls.config` is probably being overridden by the OS

**Comment by mildas** [comment]
@ggbecker most likely. The question is if we can enforce the value we need.

**Comment by mildas** [comment]
The rule also fails in `test_suite.py profile`:
`python3 test_suite.py profile --libvirt qemu:///system test_suite_vm --datastream build/ssg-rhel8-ds.xml --xccdf-id scap_org.open-scap_cref_ssg-rhel8-xccdf-1.2.xml --mode online --remediate-using oscap xccdf_org.ssgproject.content_profile_stig`

In the initial scan and the remediation phase, the rule passes. It starts to fail in the final scan. In my opinion, some other rule affects it. Otherwise I would expect it would be `fixed`/`fail`/`error` in the remediation phase.

**Comment by carlosmmatos** [comment]
so the problem with this particular rule is that the expected result of the rule is: ensure the following line is there:
`+VERS-ALL:-VERS-DTLS0.9:-VERS-SSL3.0:-VERS-TLS1.0:-VERS-TLS1.1:-VERS-DTLS1.0`

However, a few things to note:

1. By default, this is in the already desired state
2. The current issue is probably that I'm not using the regex for that line, but rather ensuring the proper default line from that file is there.. This is most likely the issue, because if the default file `gnutls.config` changes based on an updated rpm that modifies it's contents, then this will fail oval for sure.. I'm assuming your test_suite is using something greater than RHEL 8 GA which is why the contents of that file look different.

With that being said, I will re-open a new PR to address this issue - focusing on updating the OVAL, and perhaps I might need some suggestions on the best way to remediate this via ansible/bash.. I thought about doing a replace for ansible, but thought about scenarios in which that wouldn't work - ie, what's to stop someone from modifying this file? I'm guessing the likelihood of that happening is small, but it would for sure fail.

**Comment by mildas** [comment]
@carlosmmatos sorry for late response.
Yes, I'm using newer version of RHEL than RHEL 8 GA. I see that PR is already merged and I've checked the changes and look good.
We are running tests every Saturday so the update should be visible next test run. I will focus on this rule and if it is still problematic I might reopen this issue and do a bit more investigation so we have more information what's causing it.
