### ISSUE TITLE
Where are the PCI-DSS and NIST 800 high security profiles gone from ssg-ubuntu*.xml ?

### ISSUE THREAD

**Issue by huornlmj** [ComplianceAsCode/content#7297]
Past XML's had PCI DSS and NIST 800 high security profiles with hundreds of checks in them.  Now when I search through the XML files  with "oscap info" I only see basic profiles.  Where are the high security profiles gone?

**Comment by cipherboy** [comment]
@huornlmj Profiles are community-contributed content in CaC. We've slowly been developing CIS & STIG profiles in upstream CaC, but if there's something missing that you want, feel free to add it. 

Note that the ANSSI and CUI profiles from 16.04 and 18.04 aren't immediately copied over to newer releases like 20.04. You might consider starting with an older one, copying it into the 20.04 benchmark and updating it. :-) However, from what I can tell, Ubuntu never had a PCI-DSS profile in any recent version.

**Comment by huornlmj** [comment]
I see.  Around a year ago, the ssg-centos7-ds.xml stock had the following profiles:

- Title: DISA STIG for Red Hat Enterprise Linux 7
- Title: Red Hat Corporate Profile for Certified Cloud Providers (RH CCP)
- Title: Criminal Justice Information Services (CJIS) Security Policy
- Title: Health Insurance Portability and Accountability Act (HIPAA)
- Title: PCI-DSS v3 Control Baseline for Red Hat Enterprise Linux 7
- Title: C2S for Red Hat Enterprise Linux 7
- Title: Standard System Security Profile for Red Hat Enterprise Linux 7
- Title: OSPP - Protection Profile for General Purpose Operating Systems v. 4.2
- Title: United States Government Configuration Baseline
- Title: Unclassified Information in Non-federal Information Systems and Organizations (NIST 800-171)

Profiles of particular interest to me were the NIST 800-171, but as you can see there were lots of other interesting ones too.  When would or could we expect to see them available for Ubuntu?  PS I already checked the Ubuntu 14's, 16's and they only have the one standard profile also.

**Comment by cipherboy** [comment]
Ahhh so profiles are specific to each product. Unless someone contributes that particular profile to the particular product they want, it won't appear. :-) There's some work to change that (see https://github.com/ComplianceAsCode/content/discussions/6924 and https://github.com/ComplianceAsCode/content/pull/6915 for some discussion on the new "controls" format for handling benchmarks in a product-agnostic way) but at least historically, that's why the Ubuntu content never existed -- nobody upstream was contributing support for Ubuntu in particular.

We (Canonical) have no immediate plans or roadmap we can share for many of these profiles -- but we are basing future content off of CaC (see our publish CIS and STIG content so far) so if you wish to contribute such support upstream, it will eventually be supported and land in our offerings. We're also generally contributing to CaC, so a lot of changes we make will be landing here upstream and the quality of Ubuntu content should improve in the future.

**Comment by marcusburghardt** [comment]
@huornlmj , I believe your question was already answered, correct? Do you agree to close this issue? Or feel free to inform if you have any other question.
