### ISSUE TITLE
RHEL8 STIG - sssd_enable_certmap fail (remediation exists, but is not applied)

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#7403]
#### Description of problem:
The `sssd_enable_certmap` rule is not remediated in RHEL8 STIG profile.

#### SCAP Security Guide Version:
94c4fec

#### Operating System Version:
RHEL 8

#### Actual Results:
`xccdf_org.ssgproject.content_rule_sssd_enable_certmap - fail`

#### Expected Results:
`xccdf_org.ssgproject.content_rule_sssd_enable_certmap - pass`

#### Additional Information/Debugging Steps:
The rule is templated with the `lineinfile` template. However, no remediation is applied for it.

**Comment by ggbecker** [comment]
The bash/ansible remediation is turned off because the remediation does not make sense from an automation point of view:

https://github.com/ComplianceAsCode/content/blob/f2f80b4d3fe0b704e57871c5853ec3176ccb48ca/linux_os/guide/services/sssd/sssd_enable_certmap/rule.yml#L59

https://github.com/ComplianceAsCode/content/blob/f2f80b4d3fe0b704e57871c5853ec3176ccb48ca/linux_os/guide/services/sssd/sssd_enable_certmap/rule.yml#L58

We can add this to the list of rules without remediation. You may close the issue if you find this explanation good enough.

**Comment by mildas** [comment]
@ggbecker Thanks for clarification. I will add it to expected failing rules.
