### ISSUE TITLE
RHEL 7 with UEFI can't use CIS profile.

### ISSUE THREAD

**Issue by Ultimate-etamitlU** [ComplianceAsCode/content#7688]
## Which products and profiles does the rule apply to?

RHEL 7 with UEFI for CIS Profile

%addon org_fedora_oscap
    content-type = scap-security-guide
    profile = xccdf_org.ssgproject.content_profile_cis
%end

## Describe the configuration setting enforced by this rule.

It adds a blocker to VFAT as,

cat /etc/modprobe.d/vfat.conf 
Disable per security requirements
install vfat /bin/true

## Why is the configuration security relevant?

Well, On uefi based systems we really can't use CIS profile. It will create issues for booting.

## How to check the configuration?
cat /etc/modprobe.d/vfat.conf 
 Disable per security requirements
 install vfat /bin/true

**Comment by ggbecker** [comment]
Do you know exactly which version is causing this issue?

Since [v0.1.54](https://github.com/ComplianceAsCode/content/releases/tag/v0.1.54) the [kernel_module_vfat_disabled](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/permissions/mounting/kernel_module_vfat_disabled/rule.yml) is **not** present in RHEL7 CIS profile anymore. RHEL8 CIS profile had the rule removed in v0.1.55 though (https://github.com/ComplianceAsCode/content/pull/6613).
