### ISSUE TITLE
issue found in rule file permissions sshd private key

### ISSUE THREAD

**Issue by Achilleasein** [ComplianceAsCode/content#7833]
#### Description of problem:
Rule file_permissions_sshd_private_key  doesn't set the correct file permissions

#### SCAP Security Guide Version:
commit hash build: eb52609

#### Operating System Version:
RHEL8 

#### Steps to Reproduce:

1. Run the installation with kickstart
2. Run oscap after installation

#### Actual Results:
on the test run:
There are unexpected "fail" results:
xccdf_org.ssgproject.content_rule_file_permissions_sshd_private_key - fail
in the html result:
rw-r-----

#### Expected Results:
on the test run:
Test to pass
in the html results:
rw-------

**Comment by mchen-sdg** [comment]
file_permissions_sshd_private_key sets permissions to 640 and file_permissions_sshd_pub_key sets permissions to 644 even if the permissions are more restrictive. If more restrictive, should not change, 600 should remain 600, but is changed to 640 or 644.

**Comment by ggbecker** [comment]
I believe one of the causes of this issue is that during kickstart installation the key files don't exist and there is nothing to remediate. Then during the first boot these files are created with slightly wrong permissions, it works because of the `ssh_keys` group. But policies usually require the key to be 600.

The first boot remediation approach that is being developed in oscap anaconda addon may solve this kind of problem. I'm not sure exactly how to provide a fix for this.

**Comment by mildas** [comment]
Now, we waive this rule after kickstart installation, because as Becker wrote, the keys are created after installation with wrong permissions.

I'd say it's low priority issue but it would be great to approach it with first boot remediation and solve it there.

**Comment by mildas** [comment]
First boot remediation doesn't help. `sshd-keygen` service generating problematic SSH keys is executed after first boot remediation.

**Comment by matejak** [comment]
The problem is related to conflicting requirements:
CIS recommends either

- `0640` with group owner `ssh_keys`, and
- `0600` with group owner `root`,

while STIG insists on `0600` with group owner root.
The sshd script proceeds according to the user-owned keys scenario, which we can't say is wrong.

Our ideal solution would be our oscap-anaconda-addon priming sshd to set permissions according to the requirements, or it could manually trigger key generation and then assign the permission.

**Comment by mildas** [comment]
> CIS recommends either
 >   0640 with group owner ssh_keys, and
 >  0600 with group owner root

Yes, that's true.

> while STIG insists on 0600 with group owner root

No. STIG doesn't mention group at all and mode is `0640 or less permissive` https://www.stigviewer.com/stig/red_hat_enterprise_linux_8/2020-11-25/finding/V-230287 

0640 mode works only with group owner `ssh_keys`. But there might be cases where keys are generated with group owner `root` and if such keys have 0640 mode, then it prevents sshd from starting. See comment https://bugzilla.redhat.com/show_bug.cgi?id=2002850#c1


> Our ideal solution would be our oscap-anaconda-addon priming sshd to set permissions according to the requirements, or it could manually trigger key generation and then assign the permission.

Yes, or making `file_permissions_sshd_private_key` smart and check combinations of mode and ownership.

**Comment by matejak** [comment]
Great, so the rule needs to be de-templated, and its checks and remediations adjusted to either accept allowed values, or to set a preferred value if the system isn't compliant.
This is a feasible amount of work.
