### ISSUE TITLE
pam_faillock.so rules fail after remediation

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#8022]
#### Description of problem:
PAM related rules fail after hardened kickstart installation and also after clean system remediation. 

#### SCAP Security Guide Version:
05831dc

#### Operating System Version:
RHEL7, RHEL8, RHEL9

#### Steps to Reproduce:

1. `python3 tests/test_suite.py profile --libvirt qemu:///system test_suite_vm --datastream /tmp/ssg-rhel9-ds.xml --xccdf-id scap_org.open-scap_cref_ssg-rhel9-xccdf-1.2.xml --mode online --remediate-using oscap xccdf_org.ssgproject.content_profile_ospp`

#### Actual Results:
```
There are unexpected "fail" results:
xccdf_org.ssgproject.content_rule_accounts_passwords_pam_faillock_deny - fail
xccdf_org.ssgproject.content_rule_accounts_passwords_pam_faillock_deny_root - fail
xccdf_org.ssgproject.content_rule_accounts_passwords_pam_faillock_interval - fail
xccdf_org.ssgproject.content_rule_accounts_passwords_pam_faillock_unlock_time - fail
```

#### Expected Results:
PAM rules pass

**Comment by mildas** [comment]
`display_login_attempts` is also related to PAM and fails in PCI DSS profile

**Comment by TheThingGoesSkra** [comment]
By running the oscap scan after clean system remediation, using the "--verbose INFO" flag, It seems that the check is reported as FAIL because the bash script fails to run. The following error is raised by the command « authselect enable-feature with-faillock » on my side : 

 
```
[root@localhost bash]# authselect enable-feature with-faillock
[error] [/etc/authselect/system-auth] a un contenu inattendu !
[error] [/etc/authselect/password-auth] a un contenu inattendu !
[error] Des modifications inattendues de la configuration ont été détectées.
[error] Refus d’activer le profil sauf si ces modifications sont annulées ou si une demande d’écrasement est faite.
Impossible d’activer la fonctionnalité [17] : Le fichier existe
```

```
[root@localhost bash]# authselect enable-feature with-faillock
[error] [/etc/authselect/system-auth] has unexpected content!
[error] [/etc/authselect/password-auth] has unexpected content!
[error] Unexpected configuration changes have been detected.
[error] Refused to activate the profile unless these changes are undone or an override request is made.
Unable to activate the functionality [17]: The file exists
```

**Comment by marcusburghardt** [comment]
The remediations related to `pam_faillock` rely on system tools to manage pam files instead of directly editing them and consequently leaving the pam files in a inconsistent state which are impossible to be managed by system tools. The error reported is generated by the `authselect` tool, present in RHEL8, RHEL9, Fedora and OL.

Since the pam_faillock rules are already using the recommended approach, there were identified two conflicting rules which are actually doing direct edition in pam files and consequently impacting on `authselect` commands. I am working in a fix for these rules in order to make them consistent with system tools.
