### ISSUE TITLE
Some abrt rules are not applicable on RHEL8

### ISSUE THREAD

**Issue by matusmarhefka** [ComplianceAsCode/content#8286]
#### Description of problem:
Rule `package_abrt-plugin-logger_removed` should not be present on RHEL-8 as `abrt-plugin-logger` RPM is not in RHEL8 composes (it is selected in `ospp` and `stig` profiles). Other abrt rules need to be checked as well, for example `package_abrt-plugin-rhtsupport_removed` is also obsolete, `abrt-plugin-rhtsupport` RPM doesn't exist and there is rather `libreport-plugin-rhtsupport`.
Fortunately these are only minor issues the rules are about package removal and it only manifests when using SSGTS test scenarios.

#### SCAP Security Guide Version:
master

#### Operating System Version:
RHEL8

**Comment by ggbecker** [comment]
If we remove those rules from the benchmark itself it can be consider as a regression since the in theory could be used in tailoring. And I only see fixing the problem with test scenarios if the rule is not part of the benchmark anymore. Unless we provide custom test scenarios for these rules (which is awkward from my POV)
