### ISSUE TITLE
configure_bashrc_exec_tmux failing after remediation

### ISSUE THREAD

**Issue by marcusburghardt** [ComplianceAsCode/content#8913]
#### Description of problem:

The `configure_bashrc_exec_tmux` is failing after remediation

#### SCAP Security Guide Version:

master

#### Operating System Version:

RHEL8 and RHEL9

#### Actual Results:

xccdf_org.ssgproject.content_rule_configure_bashrc_exec_tmux - fail 

#### Expected Results:

xccdf_org.ssgproject.content_rule_configure_bashrc_exec_tmux - pass

**Comment by mildas** [comment]
Seems as another rule from CPE `notapplicable`->`fail` issue. Similar as `no_tmux_in_shells` or `configure_usbguard_auditbackend`.

The rule is `notapplicable` during remediation because `tmux` is not installed, thus no remediation is applied. Then during final scan when `tmux` is installed from remediations, the rule is evaluated and results in `fail`.

See #8487

**Comment by marcusburghardt** [comment]
Another question related to the processing order of the rules: #8144

**Comment by mildas** [comment]
There is no easy fix - must be fixed on scanner side.

**Comment by matusmarhefka** [comment]
Closing, reported an issue in openscap - https://github.com/OpenSCAP/openscap/issues/1880
