### ISSUE TITLE
Rule ocp4-api-server-api-priority-gate-enabled fails on clusters running OpenShift version 4.7 and later

### ISSUE THREAD

**Issue by rtheis** [ComplianceAsCode/content#9048]
#### Description of problem:

Rule [ocp4-api-server-api-priority-gate-enabled](https://github.com/ComplianceAsCode/content/blob/master/applications/openshift/api-server/api_server_api_priority_gate_enabled/rule.yml) fails on clusters running OpenShift version 4.7 and later that do not explicitly set `APIPriorityAndFairness=true`. However, Kubernetes versions 1.20 and later enable the `APIPriorityAndFairness` feature gate by default. See https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/.  Therefore, the rule should pass, not fail, by default.

#### SCAP Security Guide Version:

N/A

#### Operating System Version:

N/A

#### Steps to Reproduce:

Run the OpenShift compliance operator `ocp4-configure-network-policies` rule on a [Red Hat OpenShift on IBM Cloud](https://cloud.ibm.com/docs/openshift?topic=openshift-getting-started) cluster.

#### Actual Results:

Fail

#### Expected Results:

Pass

#### Additional Information/Debugging Steps:

N/A

**Comment by jhrozek** [comment]
This is interesting because the rule passes just fine on my OCP install. So it must be one of the places where pure OCP and IBM'S OCP diverge.
What's the output of:
```
oc get kubeapiservers/cluster -ojsonpath='{.spec.observedConfig.apiServerArguments.feature-gates}'
```
?

(That's what the rule checks for)

**Comment by rtheis** [comment]
Since the ROKS control plane is separate from the data plane, that data is not available and thus that command returns an empty string.  I think that https://github.com/openshift/api/blame/release-4.11/config/v1/types_feature.go explains the difference here.  As you can see, OCP sets `APIPriorityAndFairness` in the default enabled features even though it no longer needs to do that.

**Comment by jhrozek** [comment]
> Since the ROKS control plane is separate from the data plane, that data is not available and thus that command returns an empty string.

Right, I remember that. For some rules we (or rather @tmishina whose opinion I'd welcome here either way) modified the namespace of the resource, but this is a cluster scoped resource..

>  I think that https://github.com/openshift/api/blame/release-4.11/config/v1/types_feature.go explains the difference here. As you can see, OCP sets `APIPriorityAndFairness` in the default enabled features even though it no longer needs to do that.

Ah, thanks. And since there is no way for someone to change that default (short of rebuilding the distribution..) I tend to agree that we should change the control to inherently met and we don't have to perform the check at all.

Looking at OCP releases, already 4.7 uses kubernetes 1.20, so in theory we could mark this rule as only applicable to 4.6 or lower (but 4.6 is the oldest supported at the moment). We'd need to change our guide (note for self).
