### ISSUE TITLE
Service iptables.service is not running after reboot

### ISSUE THREAD

**Issue by yuumasato** [ComplianceAsCode/content#9190]
#### Description of problem:

After a reboot `iptables.service` which was started and  enabled by rule  `service_iptables_enabled` is not running anymore.

#### SCAP Security Guide Version:
stabilization-v0.1.63

#### Operating System Version:
RHEL-8 and RHEL-9

#### Steps to Reproduce:

1. `oscap xccdf eval --remediate --profile 'cis'  --report /tmp/report.html --oval-results --results /tmp/results.xml build/ssg-rhel8-ds.xml`
2. `systemctl status iptables.service`
```
● iptables.service - IPv4 firewall with iptables
   Loaded: loaded (/usr/lib/systemd/system/iptables.service; enabled; vendor preset: disabled)
   Active: active (exited) since Wed 2022-07-20 05:37:04 EDT; 12s ago
  Process: 6378 ExecStart=/usr/libexec/iptables/iptables.init start (code=exited, status=0/SUCCESS)
 Main PID: 6378 (code=exited, status=0/SUCCESS)

Jul 20 05:37:04 localhost.localdomain systemd[1]: Starting IPv4 firewall with iptables...
Jul 20 05:37:04 localhost.localdomain iptables.init[6378]: iptables: Applying firewall rules: [  OK  ]
Jul 20 05:37:04 localhost.localdomain systemd[1]: Started IPv4 firewall with iptables.
```
3. reboot
4. system status iptables.service
```
● iptables.service - IPv4 firewall with iptables
   Loaded: loaded (/usr/lib/systemd/system/iptables.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
```
7. 

#### Actual Results:
Rule `service_iptables_enabled` results in `fixed` during remediation, but after a reboot the rule fails.
This happens with all CIS profiles.

#### Expected Results:
After a reboot the rule should be passing, thus the service should still be running.

**Comment by marcusburghardt** [comment]
It seems it is conflicting with the `firewalld` service since `iptables` and `firewalld` can't be running at the same time.
According to the current CIS benchmark for RHEL8, one out three options can be used to manage firewall settings:
- firewalld
- iptables
- nftables

On RHEL we are in favor of `firewalld` option. So, probably the best way to solve this is to remove the `iptables` rules from the profile (move from `rule` to `related_rules` should be fine) and set a proper status value. I am not sure about which status is better there (maybe `not applicable` or `does not meet`?)

The affected requirements for now are:

- 3.4.3.1.1
- 3.4.3.2.4
- 3.4.3.2.6

There are more related requirements but they are currently in `pending` status.

**Comment by yuumasato** [comment]
I have left the Control status as `automated`, but we will need some new "thing" to better represent this in the control file.

I feel like the status is about how the control stands compared to the rule library we have in CaC, so I think it should remain as `automated` if we have rules for it.

Now, whether we will select the rules from a control is up to the profile. I think we could have something similar to what `authselect` does,  "features" that a profile could enable if desired.
For example:
RHEL8 CIS profile prefers to enable and configure `firewalld`, so the selection in `*.profile` is done like this: `- cis_rhel8:all:l2_server`.

But if one wanted to build a RHEL8 CIS profile with `iptables` instead of `firewalld`, they would just have to enable a "with-iptables" feature. e.g.: `- cis_rhel8:all:l2_server['with-iptables']` (the syntax is just an example how it could be done).

**Comment by marcusburghardt** [comment]
I agree to keep the status as `automated`.
Maybe a new issue to discuss the proposal from your comment would be nice. What do you think @yuumasato ?
