### ISSUE TITLE
Rule file_groupownership_system_commands_dirs fails when postfix is installed

### ISSUE THREAD

**Issue by yuumasato** [ComplianceAsCode/content#9249]
#### Description of problem:
Rule `file_groupownership_system_commands_dirs` checks if all files in the following directories are group owned by root:
- /sbin
- /usr/bin
- /usr/sbin
- /usr/local/bin
- /usr/local/sbin

But when  `postfix` is installed the following binaries are group owned by `postdrop` user (GID 90).
- /sbin/postdrop
- /usr/sbin/postdrop
- /usr/sbin/postqueue
- /sbin/postqueue

When remediating with the STIG profile, the rule passes.
But in subsequent scans, after postfix is installed, the rule is failing.

#### SCAP Security Guide Version:
5caa381

#### Operating System Version:
RHEL-8

#### Steps to Reproduce:

1. Remediate with STIG profile
2. Verify that rule `file_groupownership_system_commands_dirs` passes
3. Scan with the STIG profile
4. 2. Verify that rule `file_groupownership_system_commands_dirs` fails

#### Actual Results:
Rule is failing on scans after the first remediation

#### Expected Results:
Rule should be passing after first remediation

#### Additional Information/Debugging Steps:
A second remediation run would make the rule pass, it would change the groupowner of the `postfix` binaries to `postdrop`, but I don't know what effects it could have on the `postfix` service.

**Comment by yuumasato** [comment]
@marcusburghardt Do you know how postfix would behave if the binaries listed above were owned by `root` instead of `postdrop`?

**Comment by marcusburghardt** [comment]
@yuumasato , it depends on the environment.

These mentioned commands are used to manage mail queues. In the `postfix` context, each email is a file. So, when we are managing postfix queue, these commands are reading and, depending on the action, manipulating files. When something is modified by these commands, usually new files are created and replaced (like what happen with `/etc/shadow` during the the process of updating a password, just as a simple analogy). These commands might need to process a file created by other process/owner. So, they have the `SGID` permission and the `postdrop` group.

So, in a very simple environment where only the `postfix` is implemented to send internal notifications, for example, I consider a low risk of issues because the relevant files are used by the same process/owner.

However, in more complex environment when other services are integrated with `postfix`, like in an environment with `amavisd`, `spamassassin`, `opendkim`, etc, it is possible that some integration will break because these commands may not have access to relevant files. I don't remember from top of my head a specific case where this would be an issue, but I am confident this can bring issues related to permission in more complex environments.

**Comment by yuumasato** [comment]
Checking [RHEL-08-010320](https://stigs.mab879.com/products/rhel8/v1r7/RHEL-08-010320/) I see that the item expects the binaries to be group owned by root or a system account.

So the rule can be updated to check for group ids >= 0 and < 1000.
